# Generated by Django 4.2.20 on 2025-09-15 07:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField(default=0)),
                ('image', models.ImageField(default='photos/25/09/13/tour-list-4.png', upload_to='clint_photo/%y/%m/%d')),
            ],
            options={
                'verbose_name': 'clint',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(null=True)),
                ('moment', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'time',
                'ordering': ['-moment'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='enter name', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('image', models.ImageField(default='photos/25/09/13/tour-list-4.png', upload_to='photos/%y/%m/%d')),
                ('content', models.TextField(blank=True, null=True)),
                ('cotegory', models.CharField(choices=[('phone', 'phone'), ('pc', 'computer'), ('TV', 'TV'), ('car', 'car'), ('fan', 'fan')], max_length=100, verbose_name='category')),
                ('active', models.BooleanField(default=True)),
                ('product_time', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.time')),
            ],
            options={
                'verbose_name': 'product',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('place', models.CharField(choices=[('dirleen', 'dirleen'), ('cairo', 'cairo'), ('changahi', 'changahi'), ('aslamboom', 'aslambool')], max_length=100, verbose_name='market place')),
                ('vesetors', models.ManyToManyField(null=True, to='pages.clint')),
            ],
        ),
        migrations.AddField(
            model_name='clint',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.product'),
        ),
    ]
