# Generated by Django 4.2.20 on 2025-09-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='market_products',
            field=models.ManyToManyField(blank=True, null=True, to='pages.product'),
        ),
        migrations.AlterField(
            model_name='market',
            name='vesetors',
            field=models.ManyToManyField(blank=True, null=True, to='pages.clint'),
        ),
    ]
