# Generated by Django 4.2.20 on 2025-09-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_market_market_products_alter_market_vesetors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clint',
            name='product',
        ),
        migrations.AlterField(
            model_name='market',
            name='place',
            field=models.CharField(choices=[('birleen', 'birleen'), ('cairo', 'cairo'), ('changahi', 'changahi'), ('aslamboom', 'aslambool')], max_length=100, verbose_name='market place'),
        ),
        migrations.AddField(
            model_name='clint',
            name='product',
            field=models.ManyToManyField(to='pages.product'),
        ),
    ]
