# Generated by Django 4.2.20 on 2025-09-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_clint_product_alter_market_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clint',
            name='password',
            field=models.CharField(default=1234, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='cotegory',
            field=models.CharField(choices=[('phone', 'phone'), ('computer', 'computer'), ('TV', 'TV'), ('car', 'car'), ('fan', 'fan')], max_length=100, verbose_name='category'),
        ),
    ]
