# Generated by Django 4.2.20 on 2025-09-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_clint_password_alter_product_cotegory'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='market',
            name='market_products',
            field=models.ManyToManyField(blank=True, to='pages.product'),
        ),
        migrations.AlterField(
            model_name='market',
            name='vesetors',
            field=models.ManyToManyField(blank=True, to='pages.clint'),
        ),
    ]
