# Generated by Django 4.2.20 on 2025-09-21 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_market_name_alter_market_market_products_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name': 'product'},
        ),
    ]
