# Generated by Django 4.2.20 on 2025-09-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=100)),
                ('place', models.CharField(choices=[('birleen', 'birleen'), ('cairo', 'cairo'), ('changahi', 'changahi'), ('aslamboom', 'aslambool')], max_length=100, verbose_name='market place')),
            ],
        ),
    ]
