# Generated by Django 4.2.20 on 2025-09-20 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets_login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Market_login',
        ),
    ]
