# Generated by Django 4.2.20 on 2025-09-13 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_object_alter_product_options_alter_product_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
