# Generated by Django 4.2.20 on 2025-09-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_object_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
