# Generated by Django 4.2.20 on 2025-09-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_object_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='moment',
            field=models.DateTimeField(null=True),
        ),
    ]
