# Generated by Django 4.2.20 on 2025-09-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_object_moment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Object',
            new_name='Time',
        ),
        migrations.AlterField(
            model_name='product',
            name='cotegory',
            field=models.CharField(choices=[('phone', 'phone'), ('pc', 'computer'), ('TV', 'TV'), ('car', 'car'), ('fan', 'fan')], max_length=100, verbose_name='category'),
        ),
    ]
