# Generated by Django 4.2.20 on 2025-09-14 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_object_time_alter_product_cotegory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_time',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.time'),
        ),
    ]
