# Generated by Django 4.2.20 on 2025-09-14 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_product_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='time',
            options={'ordering': ['-moment'], 'verbose_name': 'time'},
        ),
    ]
