# Generated by Django 4.2.20 on 2025-09-14 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_time_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clint',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('image', models.ImageField(default='photos/25/09/13/tour-list-4.png', upload_to='clint_photo/%y/%m/%d')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
