# Generated by Django 4.2.20 on 2025-09-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_clint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clint',
            name='phone',
            field=models.BigIntegerField(default=0),
        ),
    ]
