# Generated by Django 4.2.20 on 2025-09-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_clint_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('place', models.CharField(max_length=100, verbose_name='market place')),
                ('branch', models.CharField(choices=[('dirleen', 'dirleen'), ('cairo', 'cairo'), ('changahi', 'changahi'), ('aslamboom', 'aslambool')], max_length=100, verbose_name='category')),
            ],
        ),
        migrations.AlterModelOptions(
            name='clint',
            options={'ordering': ['-name'], 'verbose_name': 'clint'},
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
