# Generated by Django 4.2.20 on 2025-09-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_market_alter_clint_options_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='vesetors',
            field=models.ManyToManyField(null=True, to='products.clint'),
        ),
    ]
