# Generated by Django 4.2.20 on 2025-09-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_market_vesetors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='branch',
        ),
        migrations.AlterField(
            model_name='market',
            name='place',
            field=models.CharField(choices=[('dirleen', 'dirleen'), ('cairo', 'cairo'), ('changahi', 'changahi'), ('aslamboom', 'aslambool')], max_length=100, verbose_name='market place'),
        ),
        migrations.AlterField(
            model_name='market',
            name='vesetors',
            field=models.ManyToManyField(to='products.clint'),
        ),
    ]
