# Generated by Django 4.2.20 on 2025-09-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_market_branch_alter_market_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='vesetors',
            field=models.ManyToManyField(null=True, to='products.clint'),
        ),
    ]
