# Generated by Django 4.2.20 on 2025-09-15 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_market_vesetors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='vesetors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_time',
        ),
        migrations.DeleteModel(
            name='Clint',
        ),
        migrations.DeleteModel(
            name='Market',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
