# Generated by Django 4.2.20 on 2025-09-16 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='market_products',
        ),
        migrations.RemoveField(
            model_name='market',
            name='vesetors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_time',
        ),
        migrations.DeleteModel(
            name='Clint',
        ),
        migrations.DeleteModel(
            name='Market',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
